### ISSUE TITLE
Copy of arduiggler repo?

### ISSUE THREAD

**Issue by zoobab** [jekkos/urjtag-st7xxx#1]
Hi,

You are linking this repo in one of your commits:

https://gitorious.org/urjtag-arduiggler

Unfortunately, Gitorious has dissappeared, and there is no copy on the internet nor archive.org of this repo.

I have a similar project here:

https://github.com/zoobab/tjtag-arduino

Which got some interest, so I wanted to know if you would still have a copy of the arduiggler GIT repo.

Best from Brussels,

**Comment by jekkos** [comment]
Hello there,

I imported the changes for arduiggler as a unified diff (patch file) at the time. I got it from the urjtag mailing lists (as it was posted there quite a while ago but never made it into the source code). Also what's missing here from the repo is the arduino sketch.

The patch worked the way it's integrated in this repository (I was able to talk to the digibox with the arduino, although transfer speed was a little slow). If you want I can send you the diff + sketch (maybe on mail?)

**Comment by zoobab** [comment]
Do you refer to this email?

http://sourceforge.net/p/urjtag/mailman/message/27192739/

**Comment by jekkos** [comment]
I think that's the one indeed. But the diff itself seems to be truncated? Maybe I did regenerate it from the original repo. I've also added the original sketch to this repo now.

**Comment by zoobab** [comment]
Thanks, just saw that recent post on using an arduino as a JTAG cable on DP:

http://dangerousprototypes.com/2015/08/19/a-jtagxsvf-library-for-arduino/

**Comment by jekkos** [comment]
Interesting link, thanks for the link. I think I did come across your website in the past, interesting infos on the bbox2 btw.
